name: Rust

on:
  push:
    branches: [ "main", "prady/ci-builds" ]
  pull_request:
    branches: [ "main", "prady/ci-builds" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: znp-build
        path: |
          target/release/node
          target/release/upgrade
          src/bin/*.toml 
          src/bin/*.json 
          src/bin/*.sh 
